version: '3.8'

services:
  aquilacms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/aquilacms
    depends_on:
      - mongo
    networks:
      - aquila-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - aquila-network

networks:
  aquila-network:
    driver: bridge

volumes:
  mongo-data: