version: '3.8'

services:
  aquilacms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DEMO_MODE=false
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/aquilacms
    depends_on:
      - mongo
    networks:
      - aquila-network
    volumes:
      - aquila-data:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - aquila-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - aquila-network
    restart: unless-stopped

networks:
  aquila-network:
    driver: bridge

volumes:
  mongo-data:
  aquila-data: